<a href="https://colab.research.google.com/github/ShoaibMuhammad123/Pytorch/blob/main/Pytorch7_A_N_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch.nn as nn
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np

In [ ]:
# set random set for reproducibility

torch.manual_seed(42)

In [ ]:
df = pd.read_csv('/content/fmnist_small.csv')

In [ ]:
df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [ ]:
x.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       1       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0        0  ...         0         7         0        50       205       196   
1        0  ...         0         0         0         0         0         0   
2        0  ...       142       142       142        21         0         3   
3        0  ...         0         0         0         0         0         0   
4        0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [ ]:
y.head()

0    9
1    7
2    0
3    8
4    8
Name: label, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [ ]:
X_train.shape

(4800, 784)

In [ ]:
X_test.shape

(1200, 784)

In [ ]:
# scaling

X_train = X_train/255
X_test =X_test/255


## **CustomDataSet Class**

In [ ]:
class CustomDataset(Dataset):

  # define constructor
  def __init__(self,features,labels):
    self.features = torch.tensor(np.array(features),dtype=torch.float32)
    self.labels = torch.tensor(np.array(labels),dtype=torch.long)

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]



In [ ]:
# creating instance of customdataset class
train_data  = CustomDataset(X_train,y_train)

In [ ]:
len(train_data)

4800

In [ ]:
test_data = CustomDataset(X_test,y_test)

In [ ]:
len(test_data)

1200

In [ ]:
# Data Loader

train_loader = DataLoader(train_data,batch_size = 32,shuffle=True)
test_loader = DataLoader(test_data,batch_size = 32,shuffle=False)

In [ ]:
for batch_feature , batch_label in train_loader:
  print(batch_feature)
  print(batch_label)
  print('*'*40)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([2, 0, 3, 9, 6, 4, 3, 3, 4, 4, 5, 1, 7, 3, 9, 8, 5, 1, 8, 6, 1, 3, 6, 1,
        2, 1, 0, 7, 3, 7, 1, 9])
****************************************
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([3, 3, 1, 8, 7, 6, 6, 5, 8, 4, 8, 6, 0, 6, 4, 1, 2, 3, 2, 4, 0, 4, 2, 1,
        4, 8, 1, 0, 7, 5, 4, 6])
****************************************
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0

In [ ]:
len(batch_feature)

32

# **Design Neural Network**

In [ ]:
class MyANN(nn.Module):
  def __init__(self,num_features):


    super().__init__()

    self.model = nn.Sequential(

        nn.Linear(num_features,128 ),
        nn.ReLU(),

        nn.Linear(128,64),
        nn.ReLU(),

        nn.Linear(64,10)
    )

# forward pass
  def forward(self,x):
    return self.model(x)



In [ ]:
# learning rate and epochs
epochs = 100
learning_rate =0.1


In [ ]:
X_train.shape

(4800, 784)

In [ ]:
batch_label.shape,batch_feature.shape, outputs.shape

(torch.Size([32]), torch.Size([32, 784]), torch.Size([32, 10]))

In [ ]:
# instantiate the object of the class
model = MyANN(X_train.shape[1])

In [ ]:
# loss function
criterion = nn.CrossEntropyLoss()

# optimizer

optimizer =torch.optim.SGD(model.parameters(),lr = learning_rate)

# **Training Pipeline**

In [ ]:
for epoch in range(epochs):

  total_epoch_loss = 0

  for batch_feature,batch_label in train_loader:

    # forward pass
    outputs = model(batch_feature)

    # loss function
    optimizer.zero_grad()
    loss = criterion(outputs , batch_label )

    # backward pass
    loss.backward()


    # update parameter
    optimizer.step()

    total_epoch_loss = total_epoch_loss+loss.item()

  avg_loss = total_epoch_loss/len(train_loader)

  print(f'Epoch: {epoch} and Loss {avg_loss}')


Epoch: 0 and Loss 1.3369920523961385
Epoch: 1 and Loss 0.7631228222449621
Epoch: 2 and Loss 0.6427521564563116
Epoch: 3 and Loss 0.5707261747121811
Epoch: 4 and Loss 0.5264454099535942
Epoch: 5 and Loss 0.48688576102256775
Epoch: 6 and Loss 0.45554029881954194
Epoch: 7 and Loss 0.4377706533670425
Epoch: 8 and Loss 0.41127018988132474
Epoch: 9 and Loss 0.4010066231091817
Epoch: 10 and Loss 0.38279902925093967
Epoch: 11 and Loss 0.3639073627193769
Epoch: 12 and Loss 0.35917372127374014
Epoch: 13 and Loss 0.3299413264294465
Epoch: 14 and Loss 0.3185665067533652
Epoch: 15 and Loss 0.30628384997447333
Epoch: 16 and Loss 0.30688674045105774
Epoch: 17 and Loss 0.2856754978497823
Epoch: 18 and Loss 0.27487884546319646
Epoch: 19 and Loss 0.2664328572154045
Epoch: 20 and Loss 0.25123802038530507
Epoch: 21 and Loss 0.2465679859618346
Epoch: 22 and Loss 0.23363154912988346
Epoch: 23 and Loss 0.22773687332868575
Epoch: 24 and Loss 0.2188415957490603
Epoch: 25 and Loss 0.21144558906555175
Epoch: 26 

In [ ]:

batch_label

tensor([9, 5, 5, 5, 5, 3, 1, 5, 4, 6, 5, 3, 3, 9, 2, 9, 5, 5, 8, 2, 5, 0, 9, 8,
        6, 4, 1, 8, 4, 6, 4, 2])

In [ ]:
# Set the model into Evaluation Mode

model.eval() # now youare in evaluation mode

MyANN(
  (model): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=10, bias=True)
  )
)

## **Evaluation Code Manually**

In [ ]:
total = 0
correct = 0

with torch.no_grad():  # No gradients are needed for testing
    for batch_feature, batch_label in test_loader:
        # Forward pass
        y_pred = model(batch_feature)

        # Get the predicted class indices
        _, predicted = torch.max(y_pred, 1)  # Use y_pred here (not outputs)

        # Ensure batch size is correctly tracked
        batch_size = batch_label.size(0)

        total += batch_size
        correct += (predicted == batch_label).sum().item()

# Calculate and print accuracy
accuracy = correct / total
print(f"Accuracy: {accuracy:.4f}")


Accuracy: 0.8433


# **Practicing own**

In [ ]:
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [ ]:
new_df = pd.read_csv('/content/fmnist_small.csv')

In [ ]:
new_df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
new_x = new_df.iloc[:,1:]
new_y = new_df.iloc[:,0]

In [ ]:
new_x.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       1       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0        0  ...         0         7         0        50       205       196   
1        0  ...         0         0         0         0         0         0   
2        0  ...       142       142       142        21         0         3   
3        0  ...         0         0         0         0         0         0   
4        0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [ ]:
new_y.head()

0    9
1    7
2    0
3    8
4    8
Name: label, dtype: int64

In [ ]:
new_df.shape

(6000, 785)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(new_x,new_y,test_size=.2,random_state=42)

In [ ]:
# scaling

x_train = x_train/255
x_test = x_test/255

In [ ]:
x_train.shape

(4800, 784)

In [ ]:
x_test.shape

(1200, 784)

# **Custom Dataset Class**

In [ ]:
class CustomDataClass(Dataset):
  def __init__(self,features,labels):

    super().__init__()
    self.features = torch.tensor(np.array(features),dtype=torch.float32)
    self.labels = torch.tensor(np.array(labels),dtype=torch.long)

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index],self.labels[index]


In [ ]:
# epochs and learning rate

epochs = 100
learning_rate = 0.1



In [ ]:
y_train

3897    7
5628    6
1756    7
2346    6
2996    8
       ..
3772    3
5191    6
5226    0
5390    8
860     6
Name: label, Length: 4800, dtype: int64

In [ ]:
# object createin
train_data = CustomDataClass(x_train,y_train)

In [ ]:
# object creatiion for test data
test_data = CustomDataClass(x_test,y_test)

In [ ]:
train_data

In [ ]:
test_data

### **Data Loaders**

In [ ]:
train_loader = DataLoader(train_data,batch_size=32,shuffle=True)
test_loader = DataLoader(test_data,batch_size=32,shuffle=False)

In [ ]:
784/32

24.5

In [ ]:
train_loader

In [ ]:
# for i , j in train_loader:

#   print(i,j)

# **Model Design**

In [ ]:
class Artificial_Neural_Network(nn.Module):

  def __init__(self,input_size):

    super().__init__()

    self.ann_model = nn.Sequential(

        nn.Linear(input_size,128),
        nn.ReLU(),

        nn.Linear(128,64),
        nn.ReLU(),

        nn.Linear(64,10)
        # nn.ReLU(),

        # nn.Linear(32,10)
    )

  def forward(self,x):

    return self.ann_model(x)


In [ ]:
# epochs and learning rate
epochs =50
learning_rate = 0.1

In [ ]:
# loss function
critersion = nn.CrossEntropyLoss()

In [ ]:
# optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

In [ ]:
model1 = Artificial_Neural_Network(x_train.shape[1])

In [ ]:
for epoch in range(epochs):

  total_epoch_loss = 0

  for batch_feature,batch_label in train_loader:

    # forward pass
    outputs = model1(batch_feature)

    # loss function
    optimizer.zero_grad()
    loss = criterion(outputs , batch_label )

    # backward pass
    loss.backward()


    # update parameter
    optimizer.step()

    total_epoch_loss = total_epoch_loss+loss.item()

  avg_loss = total_epoch_loss/len(train_loader)

  print(f'Epoch: {epoch} and Loss {avg_loss}')


Epoch: 0 and Loss 2.2955749734242756
Epoch: 1 and Loss 2.295574968655904
Epoch: 2 and Loss 2.29557497660319
Epoch: 3 and Loss 2.2955749448140463
Epoch: 4 and Loss 2.295574978192647
Epoch: 5 and Loss 2.295574986139933
Epoch: 6 and Loss 2.295574970245361
Epoch: 7 and Loss 2.295574986139933
Epoch: 8 and Loss 2.2955749734242756
Epoch: 9 and Loss 2.2955749575297038
Epoch: 10 and Loss 2.2955749622980752
Epoch: 11 and Loss 2.295574984550476
Epoch: 12 and Loss 2.295574982961019
Epoch: 13 and Loss 2.295574984550476
Epoch: 14 and Loss 2.295574984550476
Epoch: 15 and Loss 2.2955749622980752
Epoch: 16 and Loss 2.2955749797821046
Epoch: 17 and Loss 2.295574975013733
Epoch: 18 and Loss 2.295574960708618
Epoch: 19 and Loss 2.295574982961019
Epoch: 20 and Loss 2.2955749384562174
Epoch: 21 and Loss 2.295574982961019
Epoch: 22 and Loss 2.295574990908305
Epoch: 23 and Loss 2.29557497660319
Epoch: 24 and Loss 2.2955749718348186
Epoch: 25 and Loss 2.2955749543507893
Epoch: 26 and Loss 2.295574951171875
Epo

In [ ]:
batch_labels.shape,y_pred.shape

(torch.Size([32]), torch.Size([32, 10]))

In [ ]:
y_pred.shape

torch.Size([32, 10])

In [ ]:
total = 0
correct = 0

with torch.no_grad():  # No gradients are needed for testing
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model1(batch_features)

        # Get the predicted class indices
        _, predicted = torch.max(y_pred, 1)  # Use y_pred here (not outputs)

        # Ensure batch size is correctly tracked
        batch_size = batch_labels.size(0)

        total += batch_size
        correct += (predicted == batch_labels).sum().item()

# Calculate and print accuracy
accuracy = correct / total
print(f"Accuracy: {accuracy:.4f}")


Accuracy: 0.1533


## **Practicing own 2**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch


In [ ]:
# data loading

df = pd.read_csv('/content/fmnist_small.csv')

In [ ]:
df.head()

label  pixel1  pixel2  pixel3  pixel4  ...  pixel780  pixel781  pixel782  pixel783  pixel784
0      9       0       0       0       0  ...       196       213       165         0         0
1      7       0       0       0       0  ...         0         0         0         0         0
2      0       0       0       0       0  ...         3         0         0         0         0
3      8       0       0       0       0  ...         0         0         0         0         0
4      8       0       0       0       0  ...        10         0         0         0         0

[5 rows x 785 columns]

In [ ]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [ ]:
x.head(3)

pixel1  pixel2  pixel3  pixel4  pixel5  ...  pixel780  pixel781  pixel782  pixel783  pixel784
0       0       0       0       0       0  ...       196       213       165         0         0
1       0       0       0       0       0  ...         0         0         0         0         0
2       0       0       0       0       0  ...         3         0         0         0         0

[3 rows x 784 columns]

In [ ]:
y.head(3)

0    9
1    7
2    0
Name: label, dtype: int64

In [ ]:
df.shape

(6000, 785)

In [ ]:
x_train.max()

pixel1      0.000000
pixel2      0.011765
pixel3      0.023529
pixel4      0.211765
pixel5      0.635294
              ...   
pixel780    1.000000
pixel781    0.921569
pixel782    1.000000
pixel783    0.752941
pixel784    0.380392
Length: 784, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [ ]:
# scaling
x_train  = x_train /255
x_test  = x_test /255

In [ ]:
x_trian.shape

(4800, 784)

In [ ]:
x_test.shape

(1200, 784)

# **Custom Dataset Class**

In [ ]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):

    super().__init__()
    self.features = torch.tensor(np.array(features),dtype=torch.float32)
    self.labels = torch.tensor(np.array(labels),dtype=torch.long)

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index],self.labels[index]



In [ ]:
train_data = CustomDataset(x_train,y_train)
test_data = CustomDataset(x_test,y_test)

In [ ]:
train_data

# **Data Loader**

In [ ]:
new_train_loader = DataLoader(train_data,batch_size=33,shuffle=True)
new_test_loader = DataLoader(test_data,batch_size=33,shuffle=False)

In [ ]:
new_train_loader

In [ ]:
for batch_feature,batch_label in new_train_loader:
  print(batch_feature,'\n',batch_label)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) 
 tensor([1, 0, 2, 9, 7, 4, 4, 0, 1, 5, 1, 8, 1, 2, 0, 0, 6, 7, 0, 4, 2, 1, 9, 6,
        8, 6, 7, 8, 2, 5, 5, 9, 1])
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0118,  ..., 0.3216, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]) 
 tensor([5, 8, 9, 9, 3, 4, 9, 1, 0, 2, 7, 5, 0, 8, 6, 6, 3, 0, 1, 2, 7, 2, 9, 7,
        5, 1, 2, 3, 7, 3, 2, 5, 9])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0

In [ ]:
train_data[4]

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.4196, 0.2902, 0.1725, 0.1882, 0.2314, 0.3098, 0.3412, 0.3137, 0.3216,
         0.3412, 0.3882, 0.3882, 0.3137, 0.4745, 0.4549, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

# **Model Design**

In [ ]:
class MY_NN(nn.Module):

  def __init__(self,input_size):
    super().__init__()

    self.ann = nn.Sequential(
        nn.Linear(input_size,130),
        nn.ReLU(),
        nn.Linear(130,64),
        nn.ReLU(),
        nn.Linear(64,10)

    )

  def forward(self,features):
    return self.ann(features)



In [ ]:
x_train.shape[1]

784

In [ ]:
# object creation
ann = MY_NN(x_train.shape[1],)

In [ ]:
ann

MY_NN(
  (ann): Sequential(
    (0): Linear(in_features=784, out_features=130, bias=True)
    (1): ReLU()
    (2): Linear(in_features=130, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [ ]:
# epochs and learning rate
epochs =100
learning_rate =0.1



In [ ]:
# loss function
new_critersion = nn.CrossEntropyLoss()

In [ ]:
# optimizer
optimizer = torch.optim.SGD(ann.parameters(),lr = learning_rate)

## **Training Loop**

In [ ]:
for epoch in range(epochs):

  total_loss_in_epoch = 0
  for batch_input , batch_label in new_train_loader:

    # forward pass
    y_pred = ann(batch_input)

    # loss function
    optimizer.zero_grad()
    loss = new_critersion(y_pred,batch_label)

    # backward pass
    loss.backward()

    # update parameters
    optimizer.step()


    total_loss_in_epoch +=loss.item()

  new_avg_loss = total_loss_in_epoch /len(new_train_loader)
  print('Epoch: {} and Loss: {}'.format(epoch,new_avg_loss))

Epoch: 0 and Loss: 1.3730172237304792
Epoch: 1 and Loss: 0.805266676087902
Epoch: 2 and Loss: 0.6753638433675243
Epoch: 3 and Loss: 0.5962441561565007
Epoch: 4 and Loss: 0.5488156956964976
Epoch: 5 and Loss: 0.5099651823713355
Epoch: 6 and Loss: 0.47768915148630536
Epoch: 7 and Loss: 0.4506864957001111
Epoch: 8 and Loss: 0.42647178328200563
Epoch: 9 and Loss: 0.39905537481177344
Epoch: 10 and Loss: 0.39299384831157447
Epoch: 11 and Loss: 0.3605037285652879
Epoch: 12 and Loss: 0.34712065501164086
Epoch: 13 and Loss: 0.3335944414138794
Epoch: 14 and Loss: 0.32034829588071123
Epoch: 15 and Loss: 0.3133210469904828
Epoch: 16 and Loss: 0.30059328466041446
Epoch: 17 and Loss: 0.28260094919943646
Epoch: 18 and Loss: 0.2781104710310289
Epoch: 19 and Loss: 0.2612329116729024
Epoch: 20 and Loss: 0.25340638768999546
Epoch: 21 and Loss: 0.2472258160936914
Epoch: 22 and Loss: 0.23456305173570163
Epoch: 23 and Loss: 0.22359770891090777
Epoch: 24 and Loss: 0.22384461403301317
Epoch: 25 and Loss: 0.22

# **Evaluation**

### Accuracy on testing data

In [ ]:
total =0
correct = 0

with torch.no_grad():
  for batch_input ,batch_label in new_test_loader:

    y_pred = ann(batch_input)


    _,predicted = torch.max(y_pred,1)


    # ensure batch size is correctly tracked
    batch_size = batch_label.size(0)

    total+=batch_size
    correct += (predicted == batch_label).sum().item()


accuracy = correct /total
print('Accuracy :',accuracy)

Accuracy : 0.8391666666666666


### Accuracy on training data

In [ ]:
total =0
correct = 0

with torch.no_grad():
  for batch_input ,batch_label in new_train_loader:

    y_pred = ann(batch_input)


    _,predicted = torch.max(y_pred,1)


    # ensure batch size is correctly tracked
    batch_size = batch_label.size(0)

    total+=batch_size
    correct += (predicted == batch_label).sum().item()


accuracy = correct /total
print('Accuracy :',accuracy)

Accuracy : 0.9966666666666667


* This show that accuracy on training data is 99%  and testing data is 83% so, their is a huge gap