<a href="https://colab.research.google.com/github/ShoaibMuhammad123/Pytorch/blob/main/Pytorch_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
torch.empty(2,2)

tensor([[4.2111e-11, 2.6854e-06],
        [2.9571e-18, 4.3582e-41]])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.3889, 0.9049, 0.2743],
        [0.7604, 0.9807, 0.3481]])

In [ ]:
torch.tensor([3,4,4])

tensor([3, 4, 4])

In [ ]:
torch.tensor([3,4,4],dtype =torch.half)

tensor([3., 4., 4.], dtype=torch.float16)

In [ ]:
torch.tensor([3,4,4],dtype =torch.float32)

tensor([3., 4., 4.])

In [ ]:
a = torch.tensor([[23,5,3],[6,4,3]])
a

tensor([[23,  5,  3],
        [ 6,  4,  3]])

In [ ]:
b = torch.tensor([[2,4,3],[6,4,2]])
b

tensor([[2, 4, 3],
        [6, 4, 2]])

In [ ]:
a+b

tensor([[25,  9,  6],
        [12,  8,  5]])

In [ ]:
c = torch.tensor([[23,5,3],[6,4,3]],dtype=torch.float16)
c

tensor([[23.,  5.,  3.],
        [ 6.,  4.,  3.]], dtype=torch.float16)

In [ ]:
torch.ones_like(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [ ]:
torch.zeros_like(b)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(a)  # it give error because types not matcching

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.3240, 0.8507, 0.8031],
        [0.1315, 0.4531, 0.7071]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.arange(4,19,2)

tensor([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
torch.range(1,5)

<ipython-input-47-dd75ec3a47fe>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [ ]:
torch.linspace(3,9,12)

tensor([3.0000, 3.5455, 4.0909, 4.6364, 5.1818, 5.7273, 6.2727, 6.8182, 7.3636,
        7.9091, 8.4545, 9.0000])

In [ ]:
torch.logspace(1,10,3)

tensor([1.0000e+01, 3.1623e+05, 1.0000e+10])

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
c.T

tensor([[23.,  6.],
        [ 5.,  4.],
        [ 3.,  3.]], dtype=torch.float16)

In [ ]:
torch.full((3,4),8)

tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])

In [ ]:
torch.full_like(fill_value=5)

TypeError: full_like() missing 2 required positional argument: "input", "fill_value"

In [ ]:
torch.manual_seed(100)   # to get same random values
torch.rand(3,4)


tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.manual_seed(100)
a  = torch.rand(3,4)
a

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
a.shape

torch.Size([3, 4])

In [ ]:
a.ones_like()

AttributeError: 'Tensor' object has no attribute 'ones_like'

In [ ]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.zeros_like(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.manual_seed(100)
torch.rand_like(a)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

# **Mathematical Operation**

In [ ]:
b = torch.tensor([[2,3,5],[5,3,2]])
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
# scalar operation
3*b

tensor([[ 6,  9, 15],
        [15,  9,  6]])

In [ ]:
3+b

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
b+3

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
b/3

tensor([[0.6667, 1.0000, 1.6667],
        [1.6667, 1.0000, 0.6667]])

In [ ]:
(b*100)//2

tensor([[100, 150, 250],
        [250, 150, 100]])

In [ ]:
b**2

tensor([[ 4,  9, 25],
        [25,  9,  4]])

In [ ]:
d = torch.tensor([[5,3,3],[6,6,6]])
d

tensor([[5, 3, 3],
        [6, 6, 6]])

In [ ]:
b+d

tensor([[ 7,  6,  8],
        [11,  9,  8]])

In [ ]:
b*d

tensor([[10,  9, 15],
        [30, 18, 12]])

In [ ]:
b/d

tensor([[0.4000, 1.0000, 1.6667],
        [0.8333, 0.5000, 0.3333]])

In [ ]:
d1 = torch.eye(3)*3
d2 = torch.eye(3)*2


In [ ]:
d1

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [ ]:
d2

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [ ]:
d2/d1

tensor([[0.6667,    nan,    nan],
        [   nan, 0.6667,    nan],
        [   nan,    nan, 0.6667]])

In [ ]:
k = torch.tensor([-4,2,-8])
k

tensor([-4,  2, -8])

In [ ]:
torch.abs(k)

tensor([4, 2, 8])

In [ ]:
# negative
torch.neg(k)

tensor([ 4, -2,  8])

In [ ]:
# round
torch.round(a)

tensor([[0., 1., 0., 0.],
        [1., 1., 0., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.ceil(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
c = torch.tensor([3.2,3.49,3.5,3.9])   # aims is to reach integer by increasing number
c

tensor([3.2000, 3.4900, 3.5000, 3.9000])

In [ ]:
print(torch.ceil(c))

tensor([4., 4., 4., 4.])


In [ ]:
print(torch.floor(c))

tensor([3., 3., 3., 3.])


In [ ]:
d

tensor([[5, 3, 3],
        [6, 6, 6]])

In [ ]:
a

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.clamp(a,min=0.5,max=0.6)

tensor([[0.5000, 0.6000, 0.5000, 0.5000],
        [0.6000, 0.6000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.6000]])

# Reduction Operation

In [ ]:
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
torch.sum(b)

tensor(20)

In [ ]:
torch.sum(b,axis=0) # column wise

tensor([7, 6, 7])

In [ ]:
torch.sum(b,axis=1) # row wise

tensor([10, 10])

In [ ]:
torch.mean(b)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(b,dtype=torch.float32)

tensor(3.3333)

In [ ]:
torch.mean(b,dim=0,dtype=torch.float32)

tensor([3.5000, 3.0000, 3.5000])

In [ ]:
torch.median(b)

tensor(3)

In [ ]:
torch.min(b)


tensor(2)

In [ ]:
torch.max(b)


tensor(5)

In [ ]:
torch.prod(b)

tensor(900)

In [ ]:
torch.std(b,dim=1,dtype=torch.complex)

TypeError: std() received an invalid combination of arguments - got (Tensor, dtype=builtin_function_or_method, dim=int), but expected one of:
 * (Tensor input, tuple of ints dim, bool unbiased = True, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, tuple of ints dim = None, *, Number correction = None, bool keepdim = False, Tensor out = None)
 * (Tensor input, bool unbiased = True)
 * (Tensor input, tuple of names dim, bool unbiased = True, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, tuple of names dim, *, Number correction = None, bool keepdim = False, Tensor out = None)


In [ ]:
torch.var(a,  keepdim=True)

tensor([[0.0848]])

In [ ]:
torch.var(a, dim=1, keepdim=True)

tensor([[0.0935],
        [0.1145],
        [0.0877]])

In [ ]:
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
torch.argmax(b)

tensor(2)

In [ ]:
torch.argmin(b)

tensor(0)

# Matrix Multiplication

In [ ]:
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
d = d.T
d


tensor([[5, 6],
        [3, 6],
        [3, 6]])

In [ ]:
torch.matmul(b,d)

tensor([[34, 60],
        [40, 60]])

In [ ]:
c = torch.ones(3)*10

In [ ]:
c

tensor([10., 10., 10.])

In [ ]:
d = torch.ones(3)*5
d

tensor([5., 5., 5.])

In [ ]:
torch.dot(c,d)

tensor(150.)

In [ ]:
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
b1 = torch.full_like(b,3)
b1

tensor([[3, 3, 3],
        [3, 3, 3]])

In [ ]:
torch.dot(b,b1)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

# Comparison

In [ ]:
b>b1

tensor([[False, False,  True],
        [ True, False, False]])

In [ ]:
b<b1

tensor([[ True, False, False],
        [False, False,  True]])

In [ ]:
b!=b1

tensor([[ True, False,  True],
        [ True, False,  True]])

# Special function

In [ ]:
a  = torch.randint(size =(3,4),low=3,high=5)
a

tensor([[4, 4, 3, 3],
        [4, 3, 3, 4],
        [4, 4, 3, 3]])

In [ ]:
torch.log(a)

tensor([[1.3863, 1.3863, 1.0986, 1.0986],
        [1.3863, 1.0986, 1.0986, 1.3863],
        [1.3863, 1.3863, 1.0986, 1.0986]])

In [ ]:
torch.exp(a)

tensor([[54.5981, 54.5981, 20.0855, 20.0855],
        [54.5981, 20.0855, 20.0855, 54.5981],
        [54.5981, 54.5981, 20.0855, 20.0855]])

In [ ]:
torch.exp(torch.log(a))

tensor([[4., 4., 3., 3.],
        [4., 3., 3., 4.],
        [4., 4., 3., 3.]])

In [ ]:
torch.sqrt(a)

tensor([[2.0000, 2.0000, 1.7321, 1.7321],
        [2.0000, 1.7321, 1.7321, 2.0000],
        [2.0000, 2.0000, 1.7321, 1.7321]])

In [ ]:
torch.sigmoid(b)

tensor([[0.8808, 0.9526, 0.9933],
        [0.9933, 0.9526, 0.8808]])

In [ ]:
torch.softmax(b,dim=1,dtype=torch.float32)

tensor([[0.0420, 0.1142, 0.8438],
        [0.8438, 0.1142, 0.0420]])

In [ ]:
c = c*-2

In [ ]:
torch.relu(c)

tensor([0., 0., 0.])

In [ ]:
torch.relu()

# Inplace Operation

In [ ]:
b

tensor([[2, 3, 5],
        [5, 3, 2]])

In [ ]:
b1

tensor([[3, 3, 3],
        [3, 3, 3]])

In [ ]:
b.add_(b1)

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
b

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
b1

tensor([[3, 3, 3],
        [3, 3, 3]])

In [ ]:
b1.add_(2)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [ ]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [ ]:
# to make a copy of tensor we use clone function

b

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
f = b.clone()

In [ ]:
f

tensor([[5, 6, 8],
        [8, 6, 5]])

In [ ]:
b[0][0]=0

In [ ]:
b

tensor([[0, 6, 8],
        [8, 6, 5]])

In [ ]:
f

tensor([[5, 6, 8],
        [8, 6, 5]])

# Coding Tensor On GPU

In [ ]:
# to check that is gpu available
torch.cuda.is_available()

False

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
torch.tensor([[3,4,4],[4,3,2]],device = device)  # this tensor is now build on gpu

tensor([[3, 4, 4],
        [4, 3, 2]], device='cuda:0')

In [ ]:
b = torch.tensor([5,3,3])   # this tensor is build on cpu now we move it to gpu
b

tensor([5, 3, 3])

In [ ]:
b.to(device)

tensor([5, 3, 3], device='cuda:0')

In [ ]:
a = torch.randint(low= 2,high = 6,size=(1,20))
a

tensor([[5, 2, 5, 2, 4, 5, 2, 3, 4, 3, 4, 5, 2, 4, 5, 3, 5, 2, 2, 5]])

In [ ]:
a.squeeze(0)

tensor([5, 2, 5, 2, 4, 5, 2, 3, 4, 3, 4, 5, 2, 4, 5, 3, 5, 2, 2, 5])

In [ ]:
input = torch.randn(3,1,2,1,4)

In [ ]:
input

tensor([[[[[ 0.8023,  0.0768,  0.0656, -1.8861]],

          [[ 0.5937, -1.6000, -0.1521, -2.8344]]]],



        [[[[-1.3555,  0.3120, -0.8483,  1.5855]],

          [[-0.8383,  0.4187, -1.8059,  0.3600]]]],



        [[[[ 1.3522,  0.0214,  2.3222, -0.0272]],

          [[ 1.3977,  0.8906,  2.6117, -0.2199]]]]])

In [ ]:
print("Input tensor Size:\n",input.size())

# squeeze the tensor
output = torch.squeeze(input)
# print the squeezed tensor
print("Size after squeeze:\n",output)

Input tensor Size:
 torch.Size([3, 1, 2, 1, 4])
Size after squeeze:
 tensor([[[ 0.8023,  0.0768,  0.0656, -1.8861],
         [ 0.5937, -1.6000, -0.1521, -2.8344]],

        [[-1.3555,  0.3120, -0.8483,  1.5855],
         [-0.8383,  0.4187, -1.8059,  0.3600]],

        [[ 1.3522,  0.0214,  2.3222, -0.0272],
         [ 1.3977,  0.8906,  2.6117, -0.2199]]])
