<a href="https://colab.research.google.com/github/ShoaibMuhammad123/Pytorch/blob/main/Pytorch4_Training_P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()

In [ ]:
x = data.data

In [ ]:
y = data.target

In [ ]:
x[:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])

In [ ]:
columns_names = data.feature_names

In [ ]:
df = pd.DataFrame(x,columns=columns_names)

In [ ]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
df['target'] = y

In [ ]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [ ]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
x = df

In [ ]:
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 31), (114, 31), (455,), (114,))

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [ ]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  2.09724217,
         1.88645014,  0.76870611],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  1.89116053,
         2.49783848, -1.30088727],
       [-1.39998202, -1.24962228, -1.34520926, ...,  0.59760192,
         0.0578942 ,  0.76870611],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -0.70863864,
        -1.27145475,  0.76870611],
       [-0.03896885,  0.10207345, -0.03137406, ...,  0.43432185,
         1.21336207, -1.30088727],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.3345212 ,
        -0.84628745,  0.76870611]])

In [ ]:
x_test

array([[-0.46649743, -0.13728933, -0.44421138, ...,  0.17275669,
         0.20372995,  0.76870611],
       [ 1.36536344,  0.49866473,  1.30551088, ..., -0.561211  ,
        -1.00838949, -1.30088727],
       [ 0.38006578,  0.06921974,  0.40410139, ..., -0.10783139,
        -0.20629287, -1.30088727],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.3820785 ,
        -0.32408328,  0.76870611],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -1.60905688,
        -0.33137507,  0.76870611],
       [ 1.87216885,  2.80077153,  1.80354992, ..., -0.05868885,
        -0.09467243, -1.30088727]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
x_train_tensor = torch.from_numpy(x_train)

x_test_tensor = torch.from_numpy(x_test)

y_train_tensor = torch.from_numpy(y_train)

y_test_tensor = torch.from_numpy(y_test)




In [ ]:
type(x_train_tensor)

torch.Tensor

In [ ]:
type(y_train_tensor)

torch.Tensor

In [ ]:
x_train_tensor.shape

torch.Size([455, 31])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  2.0972,  1.8865,  0.7687],
        [ 1.9741,  1.7330,  2.0917,  ...,  1.8912,  2.4978, -1.3009],
        [-1.4000, -1.2496, -1.3452,  ...,  0.5976,  0.0579,  0.7687],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -0.7086, -1.2715,  0.7687],
        [-0.0390,  0.1021, -0.0314,  ...,  0.4343,  1.2134, -1.3009],
        [-0.5486,  0.3133, -0.6035,  ..., -0.3345, -0.8463,  0.7687]],
       dtype=torch.float64)

# **Defining Model**
* Defining mean desigining structure of the neural network

In [ ]:
class MyNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
    self.bias = torch.zeros(1,requires_grad=True,dtype=torch.float64)

  def forward(self,X):
    X = X.to(torch.float64)
    z = torch.matmul(X,self.weights) + self.bias

    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # clamp predictions to avoid log(0)
    epsilon =1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)


    #calculate  loss
    loss = -(y * torch.log(y_pred)+ (1- y) * torch.log(1 - y_pred)).mean()

    return loss







# **Important Parameter**

In [ ]:
learning_rate = 0.1
epochs = 25

# **Training PIPELINE**

In [ ]:
# step 1- first we create our model
model = MyNN(x_train_tensor)

# step 2 - Training model

 # define loop for epochs
for epoch in range(epochs):
  #(i): forward pass
  y_pred = model.forward(x_train_tensor)


  #(ii): loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)


  #(iii): Backward pass (here we calculate the derivatives )
  loss.backward()

  #(iv): parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epochs
  print(f'Epoch: {epoch+1}, Loss : {loss.item()}')

Epoch: 1, Loss : 2.9183290138272464
Epoch: 2, Loss : 2.7504045709468525
Epoch: 3, Loss : 2.5837401813522063
Epoch: 4, Loss : 2.4187287955774646
Epoch: 5, Loss : 2.254197857583664
Epoch: 6, Loss : 2.0963490339388566
Epoch: 7, Loss : 1.9452096997998831
Epoch: 8, Loss : 1.7994696639718408
Epoch: 9, Loss : 1.6628583035538487
Epoch: 10, Loss : 1.5375231361671922
Epoch: 11, Loss : 1.4219475453514585
Epoch: 12, Loss : 1.3184214360993909
Epoch: 13, Loss : 1.227952648554546
Epoch: 14, Loss : 1.150129901551113
Epoch: 15, Loss : 1.0841532656149095
Epoch: 16, Loss : 1.0289018048229976
Epoch: 17, Loss : 0.9830432530083011
Epoch: 18, Loss : 0.9451652953613965
Epoch: 19, Loss : 0.9139036034333032
Epoch: 20, Loss : 0.8880381085700537
Epoch: 21, Loss : 0.8665406007361437
Epoch: 22, Loss : 0.8485783761014858
Epoch: 23, Loss : 0.8334908832694081
Epoch: 24, Loss : 0.8207559711107549
Epoch: 25, Loss : 0.8099570499266567


In [ ]:
model.weights

tensor([[-0.0929],
        [ 0.4665],
        [-0.0502],
        [-0.0382],
        [ 0.1206],
        [-0.1737],
        [-0.1719],
        [-0.2380],
        [ 0.0454],
        [ 0.2965],
        [-0.0402],
        [-0.1481],
        [-0.1345],
        [ 0.5871],
        [ 0.4794],
        [ 0.0899],
        [-0.0762],
        [-0.3740],
        [ 0.4007],
        [ 0.0107],
        [ 0.4189],
        [-0.0087],
        [ 0.1924],
        [ 0.1908],
        [ 0.2999],
        [-0.4595],
        [ 0.4564],
        [ 0.2849],
        [ 0.1932],
        [ 0.2646],
        [ 1.2331]], dtype=torch.float64, requires_grad=True)

# **Model Evaluation**

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
print(y_pred)

tensor([[0.7889],
        [0.2690],
        [0.2944],
        [0.7969],
        [0.6124],
        [0.8400],
        [0.4638],
        [0.1299],
        [0.7872],
        [0.3204],
        [0.6850],
        [0.1608],
        [0.4373],
        [0.6978],
        [0.3714],
        [0.4235],
        [0.3981],
        [0.7689],
        [0.8925],
        [0.3561],
        [0.1229],
        [0.7136],
        [0.6789],
        [0.5752],
        [0.7243],
        [0.8521],
        [0.3119],
        [0.7985],
        [0.5946],
        [0.7034],
        [0.6836],
        [0.4341],
        [0.9309],
        [0.5775],
        [0.8269],
        [0.8417],
        [0.2246],
        [0.5165],
        [0.3926],
        [0.6800],
        [0.7155],
        [0.7322],
        [0.5378],
        [0.6041],
        [0.6981],
        [0.9110],
        [0.9766],
        [0.8803],
        [0.7993],
        [0.2281],
        [0.4347],
        [0.7065],
        [0.8938],
        [0.3175],
        [0.9092],
        [0

In [ ]:
df = pd.read_csv('/content/score_100.csv')

In [ ]:
df.head()

runs  form  score_100
0    28     6          0
1    48     9          1
2     9     2          0
3    55     5          1
4    17     4          0

In [ ]:
x = df.drop('score_100',axis=1)
y = df['score_100']

In [ ]:
x.head()

runs  form
0    28     6
1    48     9
2     9     2
3    55     5
4    17     4

In [ ]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: score_100, dtype: int64

# **Building own neural Network**

In [ ]:
x

runs  form
0     28     6
1     48     9
2      9     2
3     55     5
4     17     4
5     39     1
6     66     1
7     14     4
8     66     3
9     27     4
10    96     3
11     9    10
12    45     3
13    96    10
14    14     2
15    66     4
16    46     5
17    91    10
18    12     1
19    14     9
20    99     8
21    32     5
22    88     9
23     5     8
24    10     2
25    26    10
26    14     9
27    65     7
28    77     5
29    43    10
30    38     7
31    11     1
32   100     1
33    54     1
34    58     5
35    93     3
36     3    10
37     2    10
38    30     9
39    31     3
40    39     3
41    94     5
42    53     1
43    25     8
44     8    10
45     6     4
46    45     1
47    13     7
48    47     7
49    50     6

In [ ]:
y

0     0
1     1
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    1
11    1
12    0
13    1
14    0
15    1
16    1
17    1
18    0
19    1
20    1
21    0
22    1
23    0
24    0
25    1
26    1
27    1
28    1
29    1
30    1
31    0
32    1
33    0
34    1
35    1
36    1
37    1
38    1
39    0
40    0
41    1
42    0
43    1
44    1
45    0
46    0
47    0
48    1
49    1
Name: score_100, dtype: int64

In [ ]:

df

runs  form  score_100
0     28     6          0
1     48     9          1
2      9     2          0
3     55     5          1
4     17     4          0
5     39     1          0
6     66     1          0
7     14     4          0
8     66     3          0
9     27     4          0
10    96     3          1
11     9    10          1
12    45     3          0
13    96    10          1
14    14     2          0
15    66     4          1
16    46     5          1
17    91    10          1
18    12     1          0
19    14     9          1
20    99     8          1
21    32     5          0
22    88     9          1
23     5     8          0
24    10     2          0
25    26    10          1
26    14     9          1
27    65     7          1
28    77     5          1
29    43    10          1
30    38     7          1
31    11     1          0
32   100     1          1
33    54     1          0
34    58     5          1
35    93     3          1
36     3    10          1
37     2    10          1
38    30     9          1
39    31     3          0
40    39     3          0
41    94     5          1
42    53     1          0
43    25     8          1
44     8    10          1
45     6     4          0
46    45     1          0
47    13     7          0
48    47     7          1
49    50     6          1

In [ ]:
y[:6]

0    0
1    1
2    0
3    1
4    0
5    0
Name: score_100, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.1,random_state = 42)

In [ ]:
# Scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)



In [ ]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [ ]:
# to tensor
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
x_test_tensor = torch.from_numpy(x_test)

In [ ]:
x_train_tensor[:10]

tensor([[ 0.1994,  0.5501],
        [-0.9393,  1.1848],
        [-0.5253,  1.5022],
        [ 2.0282, -1.3541],
        [-0.9393,  1.1848],
        [ 0.1304, -0.7193],
        [-0.8358, -0.4020],
        [-1.3534,  1.5022],
        [ 0.8550, -0.7193],
        [ 0.4754, -0.0846]], dtype=torch.float64)

In [ ]:
x_test_tensor[:10]

tensor([[ 1.8902,  1.5022],
        [-0.3527, -0.7193],
        [-0.1112,  0.5501],
        [-1.2154, -0.4020],
        [ 1.7176,  1.5022]], dtype=torch.float64)

In [ ]:
x_train_tensor.shape

torch.Size([45, 2])

# **Model Desigining**

In [ ]:
class NN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
    self.bias = torch.zeros(1,requires_grad=True,dtype=torch.float64)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias

    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # clamp predictions to avoid log(0)
    epsilon =1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    #calculate  loss
    loss = -(y * torch.log(y_pred)+ (1- y) * torch.log(1 - y_pred)).mean()
    return loss






# **Parameters**

In [ ]:
learning_rate = 0.1
epochs = 100

# **Training pipeline**

In [ ]:
# model creation

model = NN(x_train_tensor)

# loop for epochs
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)


  # loss function
  loss = model.loss_function(y_pred,y_train_tensor)

  # Backward propagation
  loss.backward()

  # update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # set gradient to zero for next iteration
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # printing the result
  print(f'epochs: {epoch+1} Loss: {loss}')






epochs: 1 Loss: 0.798079860463975
epochs: 2 Loss: 0.7946096630287426
epochs: 3 Loss: 0.7912300074381389
epochs: 4 Loss: 0.7879393923906376
epochs: 5 Loss: 0.7847363084506667
epochs: 6 Loss: 0.7816192387914828
epochs: 7 Loss: 0.7785866600185064
epochs: 8 Loss: 0.7756370430670073
epochs: 9 Loss: 0.7727688541675226
epochs: 10 Loss: 0.7699805558719552
epochs: 11 Loss: 0.7672706081329916
epochs: 12 Loss: 0.7646374694292383
epochs: 13 Loss: 0.7620795979283453
epochs: 14 Loss: 0.7595954526803361
epochs: 15 Loss: 0.7571834948333896
epochs: 16 Loss: 0.7548421888644407
epochs: 17 Loss: 0.7525700038171317
epochs: 18 Loss: 0.7503654145398982
epochs: 19 Loss: 0.7482269029172701
epochs: 20 Loss: 0.7461529590878072
epochs: 21 Loss: 0.7441420826424916
epochs: 22 Loss: 0.7421927837978052
epochs: 23 Loss: 0.7403035845381846
epochs: 24 Loss: 0.7384730197230004
epochs: 25 Loss: 0.7366996381537045
epochs: 26 Loss: 0.7349820035972668
epochs: 27 Loss: 0.7333186957625181
epochs: 28 Loss: 0.731708311226506
epo

In [ ]:
model.bias

tensor([0.2089], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights

tensor([[0.1310],
        [0.1169]], dtype=torch.float64, requires_grad=True)

# **Model Evaluation**

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.5).float()
  print(y_pred)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [ ]:
Accuracy = (y_pred == y_test).float().mean()
print('Accuracy: ',round(Accuracy.item(),3)*100,'%')

Accuracy:  60.0 %
