<a href="https://colab.research.google.com/github/ShoaibMuhammad123/Pytorch/blob/main/Pytorch5_nn_Module_nn_optim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# **Training Pipeline Using nn.Module**

In [ ]:
# torch.nn module provide large number of classes and function designed to help
# develpoers build neural networks by offering pre-build layers,loss function,
# activation function, and other utilities enabling you to focus on designing
# and experimenting with model architectures



In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    # now we make our layers (in this case we have only one layer )
    self.linear = nn.Linear(num_features,1)    # nn.Linear(num_inputs , num_output_you_want)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [ ]:
# create data set
features = torch.rand(10,5)
# create model
model = Model(features.shape[1])

# call model forward
model(features)

tensor([[0.4571],
        [0.4226],
        [0.4841],
        [0.4625],
        [0.4698],
        [0.4397],
        [0.4753],
        [0.4627],
        [0.4564],
        [0.4613]], grad_fn=<SigmoidBackward0>)

In [ ]:
torch.rand(10,5)

tensor([[0.8730, 0.8467, 0.9848, 0.9682, 0.8731],
        [0.0936, 0.5943, 0.0161, 0.1083, 0.1099],
        [0.9676, 0.9133, 0.7992, 0.1207, 0.4825],
        [0.5893, 0.3641, 0.1318, 0.0283, 0.9649],
        [0.6062, 0.9514, 0.1844, 0.5124, 0.9517],
        [0.3993, 0.2540, 0.4048, 0.0770, 0.0466],
        [0.7919, 0.2596, 0.7671, 0.7828, 0.8561],
        [0.3073, 0.2948, 0.0454, 0.0077, 0.5909],
        [0.2181, 0.0532, 0.7953, 0.9688, 0.2627],
        [0.6119, 0.1389, 0.5538, 0.3214, 0.1965]])

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0712, -0.1175, -0.1077, -0.1983, -0.0257]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.0408], requires_grad=True)

# **Neural Network with Hidden Layer**

In [ ]:
class New_NN(nn.Module):

  def __init__(self,num_inputs):
    super().__init__()

    self.linear1 = nn.Linear(num_inputs,3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,inputs):
    out = self.linear1(inputs)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out




In [ ]:
input_data = torch.rand(10,6)
input_data

tensor([[0.0549, 0.3949, 0.9778, 0.3127, 0.2670, 0.3032],
        [0.3868, 0.3480, 0.6789, 0.9407, 0.4448, 0.9806],
        [0.4319, 0.4657, 0.1562, 0.7651, 0.1097, 0.8131],
        [0.4742, 0.9044, 0.4201, 0.8872, 0.3211, 0.6858],
        [0.1409, 0.5067, 0.7067, 0.6363, 0.0088, 0.6889],
        [0.7295, 0.7622, 0.7031, 0.6934, 0.9033, 0.7487],
        [0.4302, 0.1806, 0.9344, 0.7905, 0.1584, 0.5404],
        [0.2429, 0.0174, 0.1031, 0.4977, 0.8705, 0.1207],
        [0.5102, 0.1657, 0.4396, 0.3474, 0.6613, 0.3554],
        [0.0701, 0.8192, 0.1932, 0.0469, 0.1059, 0.5229]])

In [ ]:
model = New_NN(input_data.shape[1])
model(input_data)

tensor([[0.3770],
        [0.3741],
        [0.3629],
        [0.3684],
        [0.3681],
        [0.3840],
        [0.3700],
        [0.3632],
        [0.3682],
        [0.3629]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.0354,  0.3602, -0.1458,  0.1832, -0.3376, -0.2180],
        [-0.1054,  0.1361,  0.3498, -0.0422,  0.3091,  0.1035],
        [-0.0413,  0.1632, -0.2240, -0.0010,  0.1703, -0.2456]],
       requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0598,  0.2678, -0.0123]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.2296, -0.2645,  0.0172], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.5627], requires_grad=True)

# **Use of Sequential**

In [ ]:
class Seq_NN(nn.Module):
  def __init__(self,input_size):
    super().__init__()

    # Architecture of NN

    self.network = nn.Sequential(
        nn.Linear(input_size,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,data):
    out = self.network(data)

    return out







In [ ]:
data = torch.rand(10,5)
input_size = data.shape[1]
output_size = 3

m1 = Seq_NN(input_size)
m1(data)

tensor([[0.3612],
        [0.3404],
        [0.3672],
        [0.3536],
        [0.3894],
        [0.3512],
        [0.3509],
        [0.3626],
        [0.3628],
        [0.3701]], grad_fn=<SigmoidBackward0>)

# Creating the Pipeline for **nn.Module** for a dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/score_100.csv')

In [ ]:
df.head()

runs  form  score_100
0    28     6          0
1    48     9          1
2     9     2          0
3    55     5          1
4    17     4          0

In [ ]:
x = df.iloc[:,:2]
y = df.iloc[:,-1]

In [ ]:
x.head()

runs  form
0    28     6
1    48     9
2     9     2
3    55     5
4    17     4

In [ ]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: score_100, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.15,random_state=42)

In [ ]:
x_train.head()

runs  form
32   100     1
19    14     9
12    45     3
4     17     4
37     2    10

In [ ]:
x_test.head()




runs  form
13    96    10
39    31     3
30    38     7
45     6     4
17    91    10

In [ ]:
y_train.head()

32    1
19    1
12    0
4     0
37    1
Name: score_100, dtype: int64

In [ ]:
y_test.head()

13    1
39    0
30    1
45    0
17    1
Name: score_100, dtype: int64

In [ ]:
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = torch.tensor(x_test)

In [ ]:
x_train_tensor = torch.tensor(x_train,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
y_test_tensor = torch.tensor(x_test,dtype=torch.float32)

In [ ]:
x_train_tensor[:5]

tensor([[100.,   1.],
        [ 14.,   9.],
        [ 45.,   3.],
        [ 17.,   4.],
        [  2.,  10.]])

In [ ]:
x_test_tensor[:5]

tensor([[96., 10.],
        [31.,  3.],
        [38.,  7.],
        [ 6.,  4.],
        [91., 10.]])

### **Building Neural Network using nn.Module and Build in Activation Function**(instead of torch.sigmoid)

# **Desigining Neural Network**

In [ ]:
class NN(nn.Module):
  def __init__(self,input_size):
    super().__init__()

    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self,y_pred,y):
    # clamp predictions to avoid log(0)
    epsilon =1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)


    #calculate  loss
    loss = -(y * torch.log(y_pred)+ (1- y) * torch.log(1 - y_pred)).mean()

    return loss




In [ ]:
learning_rate =0.1
epochs = 10

In [ ]:
model = NN(x_train_tensor.shape[1])

for epoch in range(epochs):
  y_pred = model(x_train_tensor)

  # loss
  loss = model.loss_function(y_pred,y_train_tensor)

  # backward pass
  loss.backward()


  # updating parameters
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradient
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print('Epochs:{} Loss: {}'.format(epoch,loss))

Epochs:0 Loss: 2.4316046237945557
Epochs:1 Loss: 8.125398635864258
Epochs:2 Loss: 8.1065034866333
Epochs:3 Loss: 8.078990936279297
Epochs:4 Loss: 8.048691749572754
Epochs:5 Loss: 8.003144264221191
Epochs:6 Loss: 7.94523811340332
Epochs:7 Loss: 7.887954235076904
Epochs:8 Loss: 7.818944931030273
Epochs:9 Loss: 7.755234718322754


#### Now in above this code use nn module layer with out handling the weights and bias manually

## **Neural Network using build in Loss Function**

In [ ]:
class NN(nn.Module):
  def __init__(self,input_size):
    super().__init__()

    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out




In [ ]:
learning_rate =0.1
epochs = 10

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
model = NN(x_train_tensor.shape[1])

for epoch in range(epochs):
  y_pred = model(x_train_tensor)

  # loss
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()


  # updating parameters
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradient
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print('Epochs:{} Loss: {}'.format(epoch,loss))

Epochs:0 Loss: 1.4331086874008179
Epochs:1 Loss: 41.33643341064453
Epochs:2 Loss: 39.2943229675293
Epochs:3 Loss: 37.224876403808594
Epochs:4 Loss: 35.09226608276367
Epochs:5 Loss: 30.82985496520996
Epochs:6 Loss: 28.358604431152344
Epochs:7 Loss: 25.754894256591797
Epochs:8 Loss: 12.400653839111328
Epochs:9 Loss: 13.964455604553223


In [ ]:
# model Evaluation

with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred >.5).float()
  accuracy = (y_pred ==y_test_tensor).float().mean()
  print('Accuracy',accuracy.item())





Accuracy 0.0


In [ ]:
y_pred

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

# **Now we use Optimization of** ***nn.Module***

In [ ]:
# The Architecture of the model is same

class NN(nn.Module):
  def __init__(self,input_size):
    super().__init__()

    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [ ]:
learning_rate =0.1
epochs = 10

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
# for nn optimizers this this portion of code we are making changes

model = NN(x_train_tensor.shape[1])

# define optimizers
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

for epoch in range(epochs):
  y_pred = model(x_train_tensor)

  # loss
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()


  # updating parameters
  optimizer.step()

  # instead of below

  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad


  # zero gradient
  optimizer.zero_grad()

  # instead of this

  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  print('Epochs:{} Loss: {}'.format(epoch,loss))

Epochs:0 Loss: 1.6848467588424683
Epochs:1 Loss: 30.502384185791016
Epochs:2 Loss: 28.451398849487305
Epochs:3 Loss: 23.34774398803711
Epochs:4 Loss: 16.855010986328125
Epochs:5 Loss: 4.031561851501465
Epochs:6 Loss: 47.619049072265625
Epochs:7 Loss: 47.619049072265625
Epochs:8 Loss: 47.619049072265625
Epochs:9 Loss: 47.619049072265625


In [ ]:
with torch.no_grad():  # Disable gradient calculation for inference
    y_pred = model(x_test_tensor)  # Correct way to call the model
    y_pred = (y_pred > 0.5).float()  # Convert to binary predictions (0 or 1)

    accuracy = (y_pred == y_test_tensor).float().mean()  # Compute accuracy

    print('Accuracy:', accuracy.item())


Accuracy: 0.0


In [ ]:
y_pred

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [ ]:
model.linear.weight

Parameter containing:
tensor([[2.4260, 0.5096]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.5333], requires_grad=True)

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')



In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df.isnull().sum().head()

survived      0
pclass        0
sex           0
age         177
sibsp         0
dtype: int64

In [ ]:
df = df[['survived','pclass','fare']]

In [ ]:
df.head()

survived  pclass     fare
0         0       3   7.2500
1         1       1  71.2833
2         1       3   7.9250
3         1       1  53.1000
4         0       3   8.0500

In [ ]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [ ]:
x.head()

pclass     fare
0       3   7.2500
1       1  71.2833
2       3   7.9250
3       1  53.1000
4       3   8.0500

In [ ]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [ ]:
x = np.array(x)
y = np.array(y)



In [ ]:
x

array([[ 3.    ,  7.25  ],
       [ 1.    , 71.2833],
       [ 3.    ,  7.925 ],
       ...,
       [ 3.    , 23.45  ],
       [ 1.    , 30.    ],
       [ 3.    ,  7.75  ]])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [ ]:
x_train_tensor = torch.tensor(x_train,requires_grad=True,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test,requires_grad=True,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,requires_grad=True,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,requires_grad=True,dtype=torch.float32)

In [ ]:
x_train_tensor

tensor([[  1.0000,  28.5000],
        [  2.0000,  13.0000],
        [  3.0000,   7.9250],
        ...,
        [  3.0000,  14.1083],
        [  1.0000, 120.0000],
        [  1.0000,  77.2875]], requires_grad=True)

# Design NN

In [ ]:
class My_NNetwork(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out




In [ ]:
leaning_rate = 0.1
epochs = 10

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
x_train_tensor.shape[1]

2

In [ ]:
cls = My_NNetwork(x_train_tensor.shape[1])

optimizer = torch.optim.SGD(cls.parameters(),lr = learning_rate)
for epoch in range(epochs):

  y_pred = cls(x_train_tensor)

  loss = loss_function(y_pred,y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()

  # optimizer
  optimizer.step()

  # parameter update
  optimizer.zero_grad()

  print('Epoch: {} Loss: {}'.format(epoch,loss))






Epoch: 0 Loss: 10.615338325500488
Epoch: 1 Loss: 4.301997661590576
Epoch: 2 Loss: 22.26164436340332
Epoch: 3 Loss: 7.960111618041992
Epoch: 4 Loss: 9.172061920166016
Epoch: 5 Loss: 2.1580142974853516
Epoch: 6 Loss: 32.72311782836914
Epoch: 7 Loss: 26.45457649230957
Epoch: 8 Loss: 21.36492156982422
Epoch: 9 Loss: 7.015764236450195


# **Evaluation**

In [ ]:
with torch.no_grad():
    y_pred = model(x_test_tensor)
    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()

    print('Accuracy:', accuracy.item())


Accuracy: 0.4134078323841095
